
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("KinderC", "Ocean")
local Main = Window:NewTab("Ember")
local MainSection = Main:NewSection("Teleport")
MainSection:NewButton("Raion Akuma", "", function()
    teleportWorld('Raion Akuma')
end)
MainSection:NewButton("Dio Senko", "", function()
    teleportWorld('Dio Senko')
end)
MainSection:NewButton("Pts Raion", "", function()
    teleportWorld('Pts Raion')
end)
MainSection:NewButton("Bankai Akuma", "", function()
    teleportWorld('Bankai Akuma')
end)
MainSection:NewButton("Satori Akuma", "", function()
    teleportWorld('Satori Akuma')
end)
MainSection:NewButton("Forged Akuma", "", function()
    teleportWorld('Forged Akuma')
end)

local Nimbus = Window:NewTab("Nimbus")
local NimbusSection = Nimbus:NewSection("Teleport")
NimbusSection:NewButton("Ashen Storm", "", function()
    teleportWorld('Ashen Storm')
end)
NimbusSection:NewButton("Xeno Dokei", "", function()
    teleportWorld('Xeno Dokei')
end)
NimbusSection:NewButton("Giovanni Shizen", "", function()
    teleportWorld('Giovanni Shizen')
end)
NimbusSection:NewButton("Odin Saberu", "", function()
    teleportWorld('Odin Saberu')
end)

local Obelisk = Window:NewTab("Obelisk")
local ObeliskSection = Obelisk:NewSection("Teleport")
ObeliskSection:NewButton("Jizo Seishin", "", function()
    teleportWorld('Jizo Seishin')
end)
ObeliskSection:NewButton("Kabu Kobra", "", function()
    teleportWorld('Kabu Kobra')
end)
ObeliskSection:NewButton("Satoru Okami", "", function()
    teleportWorld('Satoru Okami')
end)
ObeliskSection:NewButton("Arahaki Jokei", "", function()
    teleportWorld('Arahaki Jokei')
end)
ObeliskSection:NewButton("Light Jokei", "", function()
    teleportWorld('Light Jokei')
end)

local Training = Window:NewTab("Training")
local TrainingSection = Training:NewSection("Teleport")
TrainingSection:NewButton("Ryuji Kenichi", "", function()
    teleportWorld('Ryuji Kenichi')
end)
TrainingSection:NewButton("Bruce Kenichi", "", function()
    teleportWorld('Bruce Kenichi')
end)

local Bridge = Window:NewTab("Narumaki Bridge")
local BridgeSection = Bridge:NewSection("Teleport")
BridgeSection:NewButton("Jayramaki", "", function()
    teleportWorld('Jayramaki')
end)
BridgeSection:NewButton("Borumaki", "", function()
    teleportWorld('Borumaki')
end)
BridgeSection:NewButton("Narumaki", "", function()
    teleportWorld('Narumaki')
end)
BridgeSection:NewButton("Minakaze", "", function()
    teleportWorld('Minakaze')
end)

function teleportTO(placeCFrame)
    local plyr = game.Players.LocalPlayer;
    if plyr.Character then
        plyr.Character.HumanoidRootPart.CFrame = placeCFrame;
    end
end

function teleportWorld(world)
    if game:GetService("Workspace").bossdropmission.missions:FindFirstChild(world) then
        teleportTO(game:GetService("Workspace").bossdropmission.missions[world].missiongiver.Part.CFrame)
    end
end

